### ISSUE TITLE
'_ConfigDict' object has no attribute 'test'

### ISSUE THREAD

**Issue by shaoniandelilian** [lartpang/ZoomNet#10]
Hello, I found '_ConfigDict' object has no attribute 'test' when I was executing the test code. I wonder if I could ask for your help

**Comment by lartpang** [comment]
@shaoniandelilian 

It means your final config file doesn't contain the `test` item.
You can refer to my config file: 

https://github.com/lartpang/ZoomNet/blob/1f329e80db5469eaf6a513ec384cd19bafdaece2/configs/zoomnet/cod_zoomnet.py#L44-L48

**Comment by shaoniandelilian** [comment]
尊敬的Pang先生：
&nbsp; &nbsp; &nbsp; &nbsp;首先感谢您的来信。
&nbsp; &nbsp; &nbsp; &nbsp;因为自己可能小白，还是不能很好的理解您的意思。
&nbsp; &nbsp; &nbsp; &nbsp;我想请教您一下这个问题，如果我要跑测试代码&nbsp;那么我执行的命令是&nbsp;python test.py (后面如何指定预训练好的模型和指定的测试用训练集呢？)
&nbsp; &nbsp; &nbsp; &nbsp;恳请得到您的回答。
&nbsp; &nbsp; &nbsp; &nbsp;祝您工作顺利，身体健康。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lartpang/ZoomNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月1日(星期四) 下午5:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lartpang/ZoomNet] '_ConfigDict' object has no attribute 'test' (Issue #10)





 
@shaoniandelilian
 
It means your final config file doesn't contain the test item.
 You can refer to my config file:
 
https://github.com/lartpang/ZoomNet/blob/1f329e80db5469eaf6a513ec384cd19bafdaece2/configs/zoomnet/cod_zoomnet.py#L44-L48

**Comment by lartpang** [comment]
@shaoniandelilian 你可以参考这部分文档里的内容：https://github.com/lartpang/ZoomNet#testing

具体参数设置可以看我提供的例子：https://github.com/lartpang/ZoomNet/blob/main/test.sh

这个脚本在linux上的终端里可以直接运行。
