### ISSUE TITLE
RuntimeError: unexpected EOF, expected 578749 more bytes. The file might be corrupted.

### ISSUE THREAD

**Issue by shaoniandelilian** [lartpang/ZoomNet#11]
Hello, when I was running The test code of COD task, a RuntimeError: Unexpected EOF, Expected 578749 more bytes occurred. The File might be corrupted. That is, the pre-trained model is corrupted. After many confirmations, the COD pre-training model I downloaded was 130,135,900 bytes in size. I wonder what you think about this question.

**Comment by lartpang** [comment]
@shaoniandelilian 

You are the first to encounter such a problem (:<). Here's the file info on my computer (ubuntu 18.04) that might help you locate the problem.

![image](https://user-images.githubusercontent.com/26847524/188097008-d6371a45-707f-4571-a8f3-21a1f0976af2.png)
