### ISSUE TITLE
关于HMU模块中论文和代码不一致

### ISSUE THREAD

**Issue by ponygrani** [lartpang/ZoomNet#13]
您好，论文中阐述HMU的过程是讲每次处理分裂成三组的第一个，也就是g＇¹与下一组g相加，但是代码里的操作是用g＇²相加，最后α的产生也与论文有出入，请问具体是参照哪一个，谢谢

**Comment by lartpang** [comment]
@ponygrani 关于分组的序号确实有点问题。
这一问题之前有朋友问过，可以看看这里的讨论：https://github.com/lartpang/ZoomNet/issues/2

至于您说的α的问题，可否具体一些？

---

如果论文描述令您感到疑惑，请以以代码为准。

**Comment by ponygrani** [comment]
> @ponygrani 关于分组的序号确实有点问题。 这一问题之前有朋友问过，可以看看这里的讨论：#2
> 
> 至于您说的α的问题，可否具体一些？
> 
> 如果论文描述令您感到疑惑，请以以代码为准。

谢谢您的回复，α的问题其实就是跟g的分组序号有关的，因为在论文给出的HMU模块的输出中（公式（3）），α是由g＇²经过一系列操作产生的，跟代码有出入  。 疑问已经解决了，再次感谢

**Comment by lartpang** [comment]
OK，那我就先关闭这个issue了。
