### ISSUE TITLE
关于 multi-scale training 的问题

### ISSUE THREAD

**Issue by CRRCOO** [lartpang/ZoomNet#15]
您好，在您的dataset代码中，multi-scale方法如下图：
![image](https://user-images.githubusercontent.com/48432056/226581357-eb760386-12cf-456e-a57f-dada49abbc9e.png)
![image](https://user-images.githubusercontent.com/48432056/226581376-0c6974d3-e64a-46c2-8fd7-ca0d254957fe.png)

这是否表示，不同的scale是直接从原始图像分辨率直接resize得到的。也就是说，对于1.5的scale，网络的输入分辨率实际是384\*1.5=576，也即是您的网络使用了576*576的大分辨率训练。

**Comment by lartpang** [comment]
@CRRCOO 

实际输入是三个尺度，在提取特征后，三个尺度的特征被合并到了1.0这个尺度，即384上，后续的解码器的输出和实际mask的监督都是384。

**Comment by CRRCOO** [comment]
> @CRRCOO
> 
> 实际输入是三个尺度，在提取特征后，三个尺度的特征被合并到了1.0这个尺度，即384上，后续的解码器的输出和实际mask的监督都是384。

明白了，非常感谢您的解答！
