### ISSUE TITLE
如何指定在其他显卡上跑实验？

### ISSUE THREAD

**Issue by dante1024** [lartpang/ZoomNet#18]
我在代码里指定了用别的显卡运行
然后输入这条指令
python main.py --model-name=ZoomNet --config=configs/zoomnet/zoomnet.py --datasets-info ./configs/_base_/dataset/dataset_configs.json --info demo

结果发现它还是会占用卡0的一点点显存，这是怎么回事？我想要全部搬运到其他显卡上跑实验，请问要怎么操作？

**Comment by lartpang** [comment]
@dante1024 
直接使用`CUDA_VISIBLE_DEVICES`来限制可见的GPU即可。

就像这几处使用的那样：

https://github.com/lartpang/ZoomNet/blob/1f329e80db5469eaf6a513ec384cd19bafdaece2/tools/run_it.py#L69

https://github.com/lartpang/ZoomNet/blob/1f329e80db5469eaf6a513ec384cd19bafdaece2/test.sh#L7
