### ISSUE TITLE
训练出来的指标和论文的指标差别过大

### ISSUE THREAD

**Issue by dante1024** [lartpang/ZoomNet#19]
运行main.py让它训练，代码中最后会进行测试，并把测试结果输出，
![BMX~UZIE7WC ERR0`KLT4OC](https://user-images.githubusercontent.com/60936436/229349504-a45b05d6-ede0-477a-b15b-d7226cac251d.png)

这个指标和论文相差的有点大，请问一下这是怎么回事

**Comment by lartpang** [comment]
@dante1024 

请先确保使用的依赖库的版本是一样的。正常来讲，cod10k和nc4k这两个大一点的数据集的性能是比较稳定的。

**Comment by dante1024** [comment]
> @dante1024
> 
> 请先确保使用的依赖库的版本是一样的。正常来讲，cod10k和nc4k这两个大一点的数据集的性能是比较稳定的。

我是按照您提供的依赖库版本重新安装的环境

**Comment by lartpang** [comment]
@dante1024 

按照之前的网友的反馈：https://github.com/lartpang/ZoomNet/issues/1#issuecomment-1332778380 ，只要使用相同的版本，性能的复现是没有问题的。

请问您使用的是什么GPU呢？

**Comment by dante1024** [comment]
> @dante1024
> 
> 按照之前的网友的反馈：[#1 (comment)](https://github.com/lartpang/ZoomNet/issues/1#issuecomment-1332778380) ，只要使用相同的版本，性能的复现是没有问题的。
> 
> 请问您使用的是什么GPU呢？

我的gpu是tesla P100

我在想会不会是因为您的代码中只保存最后一个epoch的模型，可能最后一个epoch的模型指标不一定是最好的那个？但是按理说就算是最后一个epoch的模型，跟论文指标差距应该不至于这么大

**Comment by lartpang** [comment]
@dante1024 
在我的实验中确实存在一定的波动，这和训练策略也有一定的关系，毕竟我这里使用了较大学习率的OneCycle形式的学习率衰减。但是我的试验里在后两个数据集上效果还是比较稳定的。
我实际训练使用的显卡是单块2080Ti，开启了混合精度。

**Comment by CoderXuzhiyu** [comment]
你们好！这是我测得的数据，我测得的四个数据集数据和作者的完全一致。
“COD10K-V3”:
{'Smeasure': '0.838', 'wFmeasure': '0.729', 'MAE': '0.029', 'adpEm': '0.893', 'meanEm': '0.888', 'maxEm': '0.911', 'adpFm': '0.741', 'meanFm': '0.766', 'maxFm': '0.780'}

顺便我想问一下，你们有关注2023cvpr上COD 的一篇新论文 Feature Shrinkage Pyramid for Camouflaged Object Detection
with Transformers吗？

这篇论文的结果我复现不出来，指标差距极大
