### ISSUE TITLE
复现问题

### ISSUE THREAD

**Issue by zhiyuxu03** [lartpang/ZoomNet#20]
您好！我是一个小白，最近我在进行复现模型的工作，但是我遇到了一个解决不了的报错：
  C:\code\pythonProject\Scripts\python.exe C:/code/pythonProject/ZoomNet-main/main.py 
C:\code\pythonProject\henv\Lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\code\pythonProject\henv\Lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\code\pythonProject\henv\Lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
Traceback (most recent call last):
  File "C:\code\pythonProject\ZoomNet-main\main.py", line 355, in <module>
    main()
  File "C:\code\pythonProject\ZoomNet-main\main.py", line 304, in main
    with open(cfg.path.cfg_copy, encoding="utf-8", mode="w") as f:
OSError: [Errno 22] Invalid argument: 'C:\\code\\pythonProject\\ZoomNet-main\\output\\ZoomNet_BS8_LR0.05_E40_H384_W384_OPMsgd_OPGMfinetune_SCf3_AMP\\cfg_2023-04-23 00:50:04.555687.py'

Process finished with exit code 1

请问一下，这个是什么问题呢？

**Comment by lartpang** [comment]
@CoderXuzhiyu 

这是你的环境配置有问题。
或许你可以先参考参考这片文章：https://blog.csdn.net/weixin_42750611/article/details/122824402

如果不行，建议按照我给出的python库的版本，在新的环境中重新配置。
一点建议：使用conda配置环境，torch系列的包（torch和cuda工具）使用conda安装（使用官方文档提供的指令），其余的包直接使用pip安装即可。

**Comment by zhiyuxu03** [comment]
您好！感谢您帮助我解决了一部分问题！

  但是上面的问题的下半部分的报错我依然无法解决：
  C:\code\pythonProject\Scripts\python.exe C:/code/pythonProject/ZoomNet-main/main.py 
Traceback (most recent call last):
  File "C:\code\pythonProject\ZoomNet-main\main.py", line 355, in <module>
    main()
  File "C:\code\pythonProject\ZoomNet-main\main.py", line 304, in main
    with open(cfg.path.cfg_copy, encoding="utf-8", mode="w") as f:
OSError: [Errno 22] Invalid argument: 'C:\\code\\pythonProject\\ZoomNet-main\\output\\ZoomNet_BS8_LR0.05_E40_H384_W384_OPMsgd_OPGMfinetune_SCf3_AMP\\cfg_2023-04-24 09:52:37.845763.py'

请问这是什么问题呢？

**Comment by lartpang** [comment]
@CoderXuzhiyu 

或许和转义符有关，可以尝试将输入的 \ 全部替换为 /

**Comment by zhiyuxu03** [comment]
您好！修改之后，好像还是类似的报错：
Traceback (most recent call last):
  File "C:\code\pythonProject\ZoomNet-main\main.py", line 355, in <module>
    main()
  File "C:\code\pythonProject\ZoomNet-main\main.py", line 304, in main
    with open(cfg.path.cfg_copy, encoding="utf-8", mode="w") as f:
OSError: [Errno 22] Invalid argument: 'C:\\code\\pythonProject\\ZoomNet-main\\output\\ZoomNet_BS8_LR0.05_E40_H384_W384_OPMsgd_OPGMfinetune_SCf3_AMP\\cfg_2023-04-27 00:38:09.498357.py'

我怀疑是文件名中出现了冒号的原因，我试着直接把cfg.copy后面的时间直接改成2023，之前的报错好像没有了，但是会出现新的报错，，，请问一下ZoomNet_BS8_LR0.05_E40_H384_W384_OPMsgd_OPGMfinetune_SCf3_AMP\\cfg_2023-04-27 00:38:09.498357.py' 这里的文件名要如何修改？

**Comment by zhiyuxu03** [comment]
请问一下，我是这样传参：
def parse_config():
    parser = argparse.ArgumentParser("Training and evaluation script")
    parser.add_argument("--config", default="C:/code/pythonProject/ZoomNet-main/configs/zoomnet/cod_zoomnet.py", type=str)
    parser.add_argument("--datasets-info", default="C:/code/pythonProject/ZoomNet-main/configs/_base_/dataset/dataset_configs.json", type=str)
    parser.add_argument("--model-name", type=str)
    parser.add_argument("--batch-size", type=int)
    parser.add_argument("--load-from", type=str)
    parser.add_argument("--resume-from", type=str)
    parser.add_argument("--info", type=str)
    args = parser.parse_args()

有什么问题吗？

**Comment by lartpang** [comment]
@CoderXuzhiyu 

传参形式本身使没问题的。windows文件名不支持以下ASCII字符：`\`, `/`, `:`, `*`, `?`, `"`, `<`, `>`, `|`

关于自动生成的文件名称是由这里配置的，你可以直接简化一下，把时间删了。

https://github.com/lartpang/ZoomNet/blob/1f329e80db5469eaf6a513ec384cd19bafdaece2/utils/misc.py#L46-L78

**Comment by CoderXuzhiyu** [comment]
您好！感谢您在这一周对我的帮助！ 训练和测试代码都跑通了，再次感谢！！

**Comment by CoderXuzhiyu** [comment]
不过，我还有几个小问题想问一下：

**Comment by zhiyuxu03** [comment]
您好！感谢您在这一周对我的帮助！！！！ 训练和测试代码我都跑通了，再次感谢！！

不过我还有几个小问题想问一下：
1.那个测试时的edge图是不是就是 那个黑白的轮廓图集？
2.模型训练时大概需要多少显存？
3.readme 那里给的权重是已经训练好的最佳权重了吗？

**Comment by lartpang** [comment]
@CoderXuzhiyu 

1. 我们的方法并没有使用edge图。
2. 我们用的是单块2080Ti。
3. 给出的是模型经过论文中说明的epoch后的最后模型，至于是否最佳，实际上更好的训练设定还会有更好的性能，但是已经不是这份工作目前所关注的内容了。

**Comment by zhiyuxu03** [comment]
好的，感谢！！
