### ISSUE TITLE
用COD10K-v3的测试集，指标差距大

### ISSUE THREAD

**Issue by L1uShuai** [lartpang/ZoomNet#21]
你好，我用COD10K-v3的测试集进行测试的时候，指标差距很大，用NC4K测试的指标是正常的。请问是什么原因？
“COD10K-V3”:
{'Smeasure': '0.851', 'wFmeasure': '0.369', 'MAE': '0.082', 'adpEm': '0.863', 'meanEm': '0.875', 'maxEm': '0.885', 'adpFm': '0.375', 'meanFm': '0.388', 'maxFm': '0.395'}
"NC4K":
{'Smeasure': '0.853', 'wFmeasure': '0.784', 'MAE': '0.043', 'adpEm': '0.907', 'meanEm': '0.896', 'maxEm': '0.912', 'adpFm': '0.814', 'meanFm': '0.818', 'maxFm': '0.828'}
是因为没有使用测试集中的背景图片以及非伪装目标的图片吗？

**Comment by lartpang** [comment]
@mkaaaa 

我们的评估方式仅仅考虑了包含伪装目标的图像。这也是其他对比方法所使用的策略。因为训练的时候也仅仅使用了包含伪装目标的图像。

**Comment by CoderXuzhiyu** [comment]
你们好！这是我测得的数据，我测得的四个数据集数据和作者的完全一致。
“COD10K-V3”:
{'Smeasure': '0.838', 'wFmeasure': '0.729', 'MAE': '0.029', 'adpEm': '0.893', 'meanEm': '0.888', 'maxEm': '0.911', 'adpFm': '0.741', 'meanFm': '0.766', 'maxFm': '0.780'}

顺便我想一下，你们有关注2023cvpr上COD 的一篇新论文 Feature Shrinkage Pyramid for Camouflaged Object Detection
with Transformers吗？

这篇论文的结果我复现不出来，指标差距极大
