### ISSUE TITLE
模型加载问题

### ISSUE THREAD

**Issue by qingwei-wang** [lartpang/ZoomNet#22]
你好，我想使用你们已经训练好的模型继续训练几轮epoch的时候，进行到这一步的时候
if cfg.resume_from:
        params_in_checkpoint = io.load_specific_params(
            load_path=cfg.resume_from, names=["model", "optimizer", "scaler", "start_epoch"]
        )
报出了这个错误
"There is not 'net_state' in ./output/ForSharing/cod_zoomnet_r50_bs8_e40_2022-03-04.pth: ['shared_encoder.conv1.weight', 

请问这个该如何解决呢？

**Comment by lartpang** [comment]
@qingwei-wang 
你好。
我自己的实验中基本不会使用这个功能。
这个恢复用的模型实际上是另一个权重文件，里面包含了这里你使用的模型参数和优化器、混合精度放缩器以及已经训练的epoch数量。可见，这个一般用于在自己完整训练过程中意外中断后的继续训练。如果想要实现你的目的，那就需要对这部分代码进行调整了。你可以自行尝试一下。
有问题可以继续留言。

**Comment by qingwei-wang** [comment]
好的，非常感谢你的回复！
