### ISSUE TITLE
关于辅助尺度的问题

### ISSUE THREAD

**Issue by xuanli98** [lartpang/ZoomNet#24]
在您的论文中，您提到，辅助尺度的图像是由主尺度的图像rescale得到的，然而您的代码是通过rescale原图像来获得1.5，1，0.5这三个尺度的图像的。如果按照您原文叙述，下采样得到主尺度然后上采样得到的1.5倍尺度的图像，这损失的细节要比直接对原图像下采样多。这样感觉1.5倍的尺度并不是辅助尺度了，而是主尺度。很感激您能解释一下我的疑惑，谢谢！
![image](https://github.com/lartpang/ZoomNet/assets/30352320/6d96e76f-4999-43f4-bc84-1c5894aca508)

![image](https://github.com/lartpang/ZoomNet/assets/30352320/89f3de04-8caa-430b-8832-ca4e1e453f81)

**Comment by lartpang** [comment]
@xuanli98 

论文中的描述有点歧义。
这里主尺度的概念应该是与最终监督的尺度有关系。模型实际训练监督仅仅使用了中间的那个特定尺度。而另两个尺度就是单纯在编码器作为辅助的参考，所以称为辅助尺度。

**Comment by xuanli98** [comment]
> @xuanli98
> 
> 论文中的描述有点歧义。 这里主尺度的概念应该是与最终监督的尺度有关系。模型实际训练监督仅仅使用了中间的那个特定尺度。而另两个尺度就是单纯在编码器作为辅助的参考，所以称为辅助尺度。

谢谢您！
