### ISSUE TITLE
数据集或训练配置

### ISSUE THREAD

**Issue by ZakaiQ** [lartpang/ZoomNet#26]
你好，我有一些复现的疑问，我采用COD10k中camouflaged的3040张数据和CAMO的1000张数据进行训练40轮次，训练测试结果与下载训练好的测试模型对比差了好几个点，是训练配置或是训练的数据集存在问题呢？

**Comment by lartpang** [comment]
@ZakaiQ 正如在之前的issue：https://github.com/lartpang/ZoomNet/issues/19#issuecomment-1493596475 中回复过的：

- 在我的实验中确实存在一定的波动，这和训练策略也有一定的关系，毕竟我这里使用了较大学习率的OneCycle形式的学习率衰减。但是我的试验里在后两个较大的数据集上效果还是比较稳定的。
- 我实际训练使用的显卡是单块2080Ti，ubuntu18.04，开启了混合精度。

**Comment by ZakaiQ** [comment]
torch版本对训练结果会有影响吗

**Comment by ZakaiQ** [comment]
#1 中提到删除了预训练的ResNet50得到最好效果，是复现结果的可行策略吗，修改位置是这里吗
`self.shared_encoder = timm.create_model(model_name="resnet50", pretrained=True, in_chans=3, features_only=True)`

**Comment by lartpang** [comment]
@ZakaiQ torch版本影响估计不大，建议直接使用timm提供的预训练权重。timm版本请与我使用的保持一致。

**Comment by ZakaiQ** [comment]
感谢您的耐心解答
