### ISSUE TITLE
数据集下载与配置

### ISSUE THREAD

**Issue by zhaolinGitHub** [lartpang/ZoomNet#4]
您好，我最近在做复现工作，数据集这块一直也没弄好。因为我相对来说还是小白，希望你们可以提供一些复现步骤的信息(数据集配置)。十分感谢

**Comment by lartpang** [comment]
@zhaolinGitHub 

关于数据集，直接从我提供的两个链接里下载即可：https://github.com/lartpang/ZoomNet#datasets
我并没有对原始数据集进行修改。

readme中的链接可能没办法直接跳转，这里附上两个更新后的链接：
- https://github.com/lartpang/awesome-segmentation-saliency-dataset#cod-camouflaged-object-detection
- https://github.com/lartpang/awesome-segmentation-saliency-dataset#rgb-saliency

数据集配置，只需要修改这个文件：https://github.com/lartpang/ZoomNet/blob/main/configs/_base_/dataset/dataset_configs.json
