### ISSUE TITLE
论文指标有问题

### ISSUE THREAD

**Issue by xmu-xiaoma666** [lartpang/ZoomNet#7]
你好，根据您提供的checkpoint，我发现您在论文中report的似乎是max E_measure，但是其他论文报的应该是mean  E_measure，这似乎是不是有点不合理

**Comment by lartpang** [comment]
> 你好，根据您提供的checkpoint，我发现您在论文中report的似乎是max E_measure，但是其他论文报的应该是mean E_measure，这似乎是不是有点不合理

只要使用相同的代码进行统一的评估汇报的话，就是可以的。
COD和SOD论文都会默认不会直接搬用原始论文的结果，而是使用所有方法的预测结果统一测试后进行汇总。
另外，我们提供了完整的预测结果和测试方法，所以想获得哪个指标都是可以的。

**Comment by xmu-xiaoma666** [comment]
> > 你好，根据您提供的checkpoint，我发现您在论文中report的似乎是max E_measure，但是其他论文报的应该是mean E_measure，这似乎是不是有点不合理
> 
> 只要使用相同的代码进行统一的评估汇报的话，就是可以的。 COD和SOD论文都会默认不会直接搬用原始论文的结果，而是使用所有方法的预测结果统一测试后进行汇总。 另外，我们提供了完整的预测结果和测试方法，所以想获得哪个指标都是可以的。

可是，论文中，其他作者report的也是max E_measure。如果不是的话，这样比较是否不太公平？

**Comment by lartpang** [comment]
@xmu-xiaoma666 

都使用相同的指标即可。
这一方式在与COD非常相关的SOD任务中也很常见。

**Comment by xmu-xiaoma666** [comment]
> @xmu-xiaoma666
> 
> 都使用相同的指标即可。 这一方式在与COD非常相关的SOD任务中也很常见。

但是其他论文E_measure报的是不是是均值？而ZoomNet这篇论文报的是最大值？

**Comment by lartpang** [comment]
@xmu-xiaoma666 
只能说我们的论文用的是maxEm。
