### ISSUE TITLE
关于模型的一些问题

### ISSUE THREAD

**Issue by GaryHuangJL** [lartpang/ZoomNet#8]
想请教问一下在ZoomNet.py中的class ZoomNet_CK是起什么作用的

**Comment by lartpang** [comment]
> 想请教问一下在ZoomNet.py中的class ZoomNet_CK是起什么作用的

这个主要是利用了checkpoint机制来压缩显存占用的。只是一个实验性的模型。

**Comment by GaryHuangJL** [comment]
十分感谢您的回复！这是否意味着，如果我想对ZoomNet的模型进行改进，只需对class ZoomNet进行改进即可

**Comment by lartpang** [comment]
@GaryHuangJL 

是的。

**Comment by GaryHuangJL** [comment]
@lartpang 非常感谢！
