### ISSUE TITLE
Extra scale

### ISSUE THREAD

**Issue by H33J1N** [lartpang/ZoomNet#9]
Hi. I'm impressed by your awesome zoomnet method. And I have a question about the code.
On sod_zoomnet config, there's a config name ms.exta_size. And the config is used on baseSODdataset. And the annotation explain the value as "extra-scale for multi-scale learning". But I can't find the usage of these extra-scale information.
Because the model gets the data consist of only 1.5, 1.0, 0.5.
Therefore, could you explain the details and usage of extra-scale size? Thank you.

**Comment by lartpang** [comment]
@H33J1N 

Hi, please see the method `collate_fn` at: https://github.com/lartpang/ZoomNet/blob/1f329e80db5469eaf6a513ec384cd19bafdaece2/dataset/base_dataset.py#L90-L95

Here, a scale will be randomly sampled from the preset scale set to adjust the size of the entire batch.
